version: "2"

services:
  edge:
    image: envoyproxy/envoy:v1.13-latest
    ports:
      - "8080:8080"
      - "8001:8001"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml  
      - ./certs:/certs

  server-1:
    image: kaitmore/sse-server:latest
    ports:
      - "7081:7081"
    volumes:
      - ./certs:/certs
    environment:
      - PORT=7081
      - DATA_ENDPOINT=https://icanhazdadjoke.com/
      - EVENT_TYPE=server1
      - CERT_PATH=/certs/localhost.crt
      - KEY_PATH=/certs/localhost.key

  server-2:
    image: kaitmore/sse-server:latest
    ports:
      - "6081:6081"
    volumes:
      - ./certs:/certs
    environment:
      - PORT=6081
      - DATA_ENDPOINT=https://icanhazdadjoke.com/
      - EVENT_TYPE=server2
      - CERT_PATH=/certs/localhost.crt
      - KEY_PATH=/certs/localhost.key

  client: 
    image: kaitmore/sse-client:latest
    ports: 
      - "8081:8081"
    volumes:
      - ./certs:/certs
    environment:
      - PORT=8081
      - CERT_PATH=/certs/localhost.crt
      - KEY_PATH=/certs/localhost.key


  authz:
    build:
      context: ./auth
    expose:
      - "9090"
    ports:
      - "9090:9090"
    volumes:
      - "./auth/keycloak.json:/usr/src/app/keycloak.json"
    environment: 
      - CLIENT_SECRET=19cd1ab7-343b-46fc-b620-895cb21f4b79

  keycloak:
    image: jboss/keycloak:8.0.1
    volumes:
      - "./auth/setup-keycloak.sh:/opt/jboss/setup-keycloak.sh"
    ports:
      - "7777:8080"
    environment:
      - KEYCLOAK_USER=user
      - KEYCLOAK_PASSWORD=password
      - DB_VENDOR=H2